name: Prevent ByteOrderMarks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  bom-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arma-actions/bom-check@v1
        name: Check for BOM
  
